document.addEventListener('DOMContentLoaded', () => {
  const explanationMethods = document.querySelectorAll('.explanation-method');
  const resultsElement = document.getElementById('results');

  explanationMethods.forEach((method) => {
    setTimeout(() => {
      method.classList.add('moving');
    }, 1000);
  });

  setTimeout(() => {
    resultsElement.innerHTML = `
      <p>84% of interview participants reported encountering the disagreement problem in their day-to-day workflow.</p>
      <p>Our empirical analysis confirmed that explanations generated by state-of-the-art methods often disagree with each other.</p>
      <p>86% of online user study responses indicated that ML practitioners either employed arbitrary heuristics or did not know how to resolve the disagreement problem.</p>
    `;
  }, 3000);
});